//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-DA92CAH\\SQLEXPRESS01;Initial Catalog=QLDVRESORT;User ID=sa;Pa" +
            "ssword=123")]
        public string QLDVRESORTConnectionString {
            get {
                return ((string)(this["QLDVRESORTConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-ED5PBNKM;Initial Catalog=QLDVRESORT;Persist Security Info=True" +
            ";User ID=sa")]
        public string QLDVRESORTConnectionString1 {
            get {
                return ((string)(this["QLDVRESORTConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-ED5PBNKM;Initial Catalog=QLDVRESORT;Persist Security Info=True" +
            ";User ID=sa;Password=sa123")]
        public string QLDVRESORTConnectionString2 {
            get {
                return ((string)(this["QLDVRESORTConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-DA92CAH\\SQLEXPRESS01;Initial Catalog=QLDVRESORT;Persist Secur" +
            "ity Info=True;User ID=sa;Password=123")]
        public string QLDVRESORTConnectionString3 {
            get {
                return ((string)(this["QLDVRESORTConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHTHIEN-1702\\SQLEXPRESS01;Initial Catalog=QLDVRESORT;User ID=sa;Pa" +
            "ssword=123")]
        public string QLDVRESORTConnectionString4 {
            get {
                return ((string)(this["QLDVRESORTConnectionString4"]));
            }
        }
    }
}
