#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDVRESORT")]
	public partial class QLDVRSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdatphong(datphong instance);
    partial void Updatedatphong(datphong instance);
    partial void Deletedatphong(datphong instance);
    partial void Insertdichvu(dichvu instance);
    partial void Updatedichvu(dichvu instance);
    partial void Deletedichvu(dichvu instance);
    partial void Insertdoiphong(doiphong instance);
    partial void Updatedoiphong(doiphong instance);
    partial void Deletedoiphong(doiphong instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertkhachsan(khachsan instance);
    partial void Updatekhachsan(khachsan instance);
    partial void Deletekhachsan(khachsan instance);
    partial void Insertloaiphong(loaiphong instance);
    partial void Updateloaiphong(loaiphong instance);
    partial void Deleteloaiphong(loaiphong instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertquyen(quyen instance);
    partial void Updatequyen(quyen instance);
    partial void Deletequyen(quyen instance);
    partial void Insertphong(phong instance);
    partial void Updatephong(phong instance);
    partial void Deletephong(phong instance);
    partial void InsertThaoTacDatPhong(ThaoTacDatPhong instance);
    partial void UpdateThaoTacDatPhong(ThaoTacDatPhong instance);
    partial void DeleteThaoTacDatPhong(ThaoTacDatPhong instance);
    partial void Insertthietbi(thietbi instance);
    partial void Updatethietbi(thietbi instance);
    partial void Deletethietbi(thietbi instance);
    #endregion
		
		public QLDVRSDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLDVRESORTConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVRSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVRSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVRSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDVRSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chitietsudungdv> chitietsudungdvs
		{
			get
			{
				return this.GetTable<chitietsudungdv>();
			}
		}
		
		public System.Data.Linq.Table<chitietsudungtb> chitietsudungtbs
		{
			get
			{
				return this.GetTable<chitietsudungtb>();
			}
		}
		
		public System.Data.Linq.Table<datphong> datphongs
		{
			get
			{
				return this.GetTable<datphong>();
			}
		}
		
		public System.Data.Linq.Table<dichvu> dichvus
		{
			get
			{
				return this.GetTable<dichvu>();
			}
		}
		
		public System.Data.Linq.Table<doiphong> doiphongs
		{
			get
			{
				return this.GetTable<doiphong>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<khachsan> khachsans
		{
			get
			{
				return this.GetTable<khachsan>();
			}
		}
		
		public System.Data.Linq.Table<loaiphong> loaiphongs
		{
			get
			{
				return this.GetTable<loaiphong>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<quyen> quyens
		{
			get
			{
				return this.GetTable<quyen>();
			}
		}
		
		public System.Data.Linq.Table<phong> phongs
		{
			get
			{
				return this.GetTable<phong>();
			}
		}
		
		public System.Data.Linq.Table<ThaoTacDatPhong> ThaoTacDatPhongs
		{
			get
			{
				return this.GetTable<ThaoTacDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<thietbi> thietbis
		{
			get
			{
				return this.GetTable<thietbi>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietsudungdv")]
	public partial class chitietsudungdv
	{
		
		private string _id_datphong;
		
		private string _id_dichvu;
		
		private System.Nullable<System.DateTime> _ngay_thue;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<double> _tong_tien_dv;
		
		public chitietsudungdv()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_datphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_datphong
		{
			get
			{
				return this._id_datphong;
			}
			set
			{
				if ((this._id_datphong != value))
				{
					this._id_datphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dichvu", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_dichvu
		{
			get
			{
				return this._id_dichvu;
			}
			set
			{
				if ((this._id_dichvu != value))
				{
					this._id_dichvu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_thue", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_thue
		{
			get
			{
				return this._ngay_thue;
			}
			set
			{
				if ((this._ngay_thue != value))
				{
					this._ngay_thue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this._so_luong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien_dv", DbType="Float")]
		public System.Nullable<double> tong_tien_dv
		{
			get
			{
				return this._tong_tien_dv;
			}
			set
			{
				if ((this._tong_tien_dv != value))
				{
					this._tong_tien_dv = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietsudungtb")]
	public partial class chitietsudungtb
	{
		
		private string _id_datphong;
		
		private string _id_thietbi;
		
		private System.Nullable<System.DateTime> _ngay_thue;
		
		private System.Nullable<int> _so_luong;
		
		private System.Nullable<double> _tong_tien_tb;
		
		public chitietsudungtb()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_datphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_datphong
		{
			get
			{
				return this._id_datphong;
			}
			set
			{
				if ((this._id_datphong != value))
				{
					this._id_datphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thietbi", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_thietbi
		{
			get
			{
				return this._id_thietbi;
			}
			set
			{
				if ((this._id_thietbi != value))
				{
					this._id_thietbi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_thue", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_thue
		{
			get
			{
				return this._ngay_thue;
			}
			set
			{
				if ((this._ngay_thue != value))
				{
					this._ngay_thue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this._so_luong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien_tb", DbType="Float")]
		public System.Nullable<double> tong_tien_tb
		{
			get
			{
				return this._tong_tien_tb;
			}
			set
			{
				if ((this._tong_tien_tb != value))
				{
					this._tong_tien_tb = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.datphong")]
	public partial class datphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_datphong;
		
		private string _id_nhanvien;
		
		private string _id_khachhang;
		
		private string _id_phong;
		
		private System.DateTime _check_in;
		
		private System.Nullable<System.DateTime> _check_out;
		
		private System.Nullable<double> _dat_coc;
		
		private System.Nullable<double> _phu_thu_checkin;
		
		private System.Nullable<double> _phu_thu_checkout;
		
		private System.Nullable<int> _so_nguoi_o;
		
		private string _trang_thai;
		
		private System.Nullable<System.DateTime> _ngaydat;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<nhanvien> _nhanvien;
		
		private EntityRef<phong> _phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_datphongChanging(string value);
    partial void Onid_datphongChanged();
    partial void Onid_nhanvienChanging(string value);
    partial void Onid_nhanvienChanged();
    partial void Onid_khachhangChanging(string value);
    partial void Onid_khachhangChanged();
    partial void Onid_phongChanging(string value);
    partial void Onid_phongChanged();
    partial void Oncheck_inChanging(System.DateTime value);
    partial void Oncheck_inChanged();
    partial void Oncheck_outChanging(System.Nullable<System.DateTime> value);
    partial void Oncheck_outChanged();
    partial void Ondat_cocChanging(System.Nullable<double> value);
    partial void Ondat_cocChanged();
    partial void Onphu_thu_checkinChanging(System.Nullable<double> value);
    partial void Onphu_thu_checkinChanged();
    partial void Onphu_thu_checkoutChanging(System.Nullable<double> value);
    partial void Onphu_thu_checkoutChanged();
    partial void Onso_nguoi_oChanging(System.Nullable<int> value);
    partial void Onso_nguoi_oChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void OnngaydatChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydatChanged();
    #endregion
		
		public datphong()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._khachhang = default(EntityRef<khachhang>);
			this._nhanvien = default(EntityRef<nhanvien>);
			this._phong = default(EntityRef<phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_datphong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_datphong
		{
			get
			{
				return this._id_datphong;
			}
			set
			{
				if ((this._id_datphong != value))
				{
					this.Onid_datphongChanging(value);
					this.SendPropertyChanging();
					this._id_datphong = value;
					this.SendPropertyChanged("id_datphong");
					this.Onid_datphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_khachhang
		{
			get
			{
				return this._id_khachhang;
			}
			set
			{
				if ((this._id_khachhang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khachhangChanging(value);
					this.SendPropertyChanging();
					this._id_khachhang = value;
					this.SendPropertyChanged("id_khachhang");
					this.Onid_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_phong
		{
			get
			{
				return this._id_phong;
			}
			set
			{
				if ((this._id_phong != value))
				{
					if (this._phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_phongChanging(value);
					this.SendPropertyChanging();
					this._id_phong = value;
					this.SendPropertyChanged("id_phong");
					this.Onid_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_in", DbType="DateTime NOT NULL")]
		public System.DateTime check_in
		{
			get
			{
				return this._check_in;
			}
			set
			{
				if ((this._check_in != value))
				{
					this.Oncheck_inChanging(value);
					this.SendPropertyChanging();
					this._check_in = value;
					this.SendPropertyChanged("check_in");
					this.Oncheck_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_check_out", DbType="DateTime")]
		public System.Nullable<System.DateTime> check_out
		{
			get
			{
				return this._check_out;
			}
			set
			{
				if ((this._check_out != value))
				{
					this.Oncheck_outChanging(value);
					this.SendPropertyChanging();
					this._check_out = value;
					this.SendPropertyChanged("check_out");
					this.Oncheck_outChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_coc", DbType="Float")]
		public System.Nullable<double> dat_coc
		{
			get
			{
				return this._dat_coc;
			}
			set
			{
				if ((this._dat_coc != value))
				{
					this.Ondat_cocChanging(value);
					this.SendPropertyChanging();
					this._dat_coc = value;
					this.SendPropertyChanged("dat_coc");
					this.Ondat_cocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phu_thu_checkin", DbType="Float")]
		public System.Nullable<double> phu_thu_checkin
		{
			get
			{
				return this._phu_thu_checkin;
			}
			set
			{
				if ((this._phu_thu_checkin != value))
				{
					this.Onphu_thu_checkinChanging(value);
					this.SendPropertyChanging();
					this._phu_thu_checkin = value;
					this.SendPropertyChanged("phu_thu_checkin");
					this.Onphu_thu_checkinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phu_thu_checkout", DbType="Float")]
		public System.Nullable<double> phu_thu_checkout
		{
			get
			{
				return this._phu_thu_checkout;
			}
			set
			{
				if ((this._phu_thu_checkout != value))
				{
					this.Onphu_thu_checkoutChanging(value);
					this.SendPropertyChanging();
					this._phu_thu_checkout = value;
					this.SendPropertyChanged("phu_thu_checkout");
					this.Onphu_thu_checkoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_nguoi_o", DbType="Int")]
		public System.Nullable<int> so_nguoi_o
		{
			get
			{
				return this._so_nguoi_o;
			}
			set
			{
				if ((this._so_nguoi_o != value))
				{
					this.Onso_nguoi_oChanging(value);
					this.SendPropertyChanging();
					this._so_nguoi_o = value;
					this.SendPropertyChanged("so_nguoi_o");
					this.Onso_nguoi_oChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(40)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydat
		{
			get
			{
				return this._ngaydat;
			}
			set
			{
				if ((this._ngaydat != value))
				{
					this.OnngaydatChanging(value);
					this.SendPropertyChanging();
					this._ngaydat = value;
					this.SendPropertyChanged("ngaydat");
					this.OnngaydatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="datphong_hoadon", Storage="_hoadons", ThisKey="id_datphong", OtherKey="id_datphong")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_datphong", Storage="_khachhang", ThisKey="id_khachhang", OtherKey="id_khachhang", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.datphongs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.datphongs.Add(this);
						this._id_khachhang = value.id_khachhang;
					}
					else
					{
						this._id_khachhang = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_datphong", Storage="_nhanvien", ThisKey="id_nhanvien", OtherKey="id_nhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.datphongs.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.datphongs.Add(this);
						this._id_nhanvien = value.id_nhanvien;
					}
					else
					{
						this._id_nhanvien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_datphong", Storage="_phong", ThisKey="id_phong", OtherKey="id_phong", IsForeignKey=true)]
		public phong phong
		{
			get
			{
				return this._phong.Entity;
			}
			set
			{
				phong previousValue = this._phong.Entity;
				if (((previousValue != value) 
							|| (this._phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phong.Entity = null;
						previousValue.datphongs.Remove(this);
					}
					this._phong.Entity = value;
					if ((value != null))
					{
						value.datphongs.Add(this);
						this._id_phong = value.id_phong;
					}
					else
					{
						this._id_phong = default(string);
					}
					this.SendPropertyChanged("phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.datphong = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.datphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dichvu")]
	public partial class dichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_dichvu;
		
		private string _ten_dichvu;
		
		private int _gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_dichvuChanging(string value);
    partial void Onid_dichvuChanged();
    partial void Onten_dichvuChanging(string value);
    partial void Onten_dichvuChanged();
    partial void OngiaChanging(int value);
    partial void OngiaChanged();
    #endregion
		
		public dichvu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_dichvu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_dichvu
		{
			get
			{
				return this._id_dichvu;
			}
			set
			{
				if ((this._id_dichvu != value))
				{
					this.Onid_dichvuChanging(value);
					this.SendPropertyChanging();
					this._id_dichvu = value;
					this.SendPropertyChanged("id_dichvu");
					this.Onid_dichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dichvu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dichvu
		{
			get
			{
				return this._ten_dichvu;
			}
			set
			{
				if ((this._ten_dichvu != value))
				{
					this.Onten_dichvuChanging(value);
					this.SendPropertyChanging();
					this._ten_dichvu = value;
					this.SendPropertyChanged("ten_dichvu");
					this.Onten_dichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Int NOT NULL")]
		public int gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.doiphong")]
	public partial class doiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_doiphong;
		
		private string _id_phong_bandau;
		
		private string _id_phong_doiphong;
		
		private string _id_nhanvien_thuchien;
		
		private System.Nullable<System.DateTime> _ngaythuchien;
		
		private string _lydodoiphong;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_doiphongChanging(int value);
    partial void Onid_doiphongChanged();
    partial void Onid_phong_bandauChanging(string value);
    partial void Onid_phong_bandauChanged();
    partial void Onid_phong_doiphongChanging(string value);
    partial void Onid_phong_doiphongChanged();
    partial void Onid_nhanvien_thuchienChanging(string value);
    partial void Onid_nhanvien_thuchienChanged();
    partial void OnngaythuchienChanging(System.Nullable<System.DateTime> value);
    partial void OnngaythuchienChanged();
    partial void OnlydodoiphongChanging(string value);
    partial void OnlydodoiphongChanged();
    #endregion
		
		public doiphong()
		{
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_doiphong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_doiphong
		{
			get
			{
				return this._id_doiphong;
			}
			set
			{
				if ((this._id_doiphong != value))
				{
					this.Onid_doiphongChanging(value);
					this.SendPropertyChanging();
					this._id_doiphong = value;
					this.SendPropertyChanged("id_doiphong");
					this.Onid_doiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phong_bandau", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_phong_bandau
		{
			get
			{
				return this._id_phong_bandau;
			}
			set
			{
				if ((this._id_phong_bandau != value))
				{
					this.Onid_phong_bandauChanging(value);
					this.SendPropertyChanging();
					this._id_phong_bandau = value;
					this.SendPropertyChanged("id_phong_bandau");
					this.Onid_phong_bandauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phong_doiphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_phong_doiphong
		{
			get
			{
				return this._id_phong_doiphong;
			}
			set
			{
				if ((this._id_phong_doiphong != value))
				{
					this.Onid_phong_doiphongChanging(value);
					this.SendPropertyChanging();
					this._id_phong_doiphong = value;
					this.SendPropertyChanged("id_phong_doiphong");
					this.Onid_phong_doiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien_thuchien", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_nhanvien_thuchien
		{
			get
			{
				return this._id_nhanvien_thuchien;
			}
			set
			{
				if ((this._id_nhanvien_thuchien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvien_thuchienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien_thuchien = value;
					this.SendPropertyChanged("id_nhanvien_thuchien");
					this.Onid_nhanvien_thuchienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythuchien", DbType="Date")]
		public System.Nullable<System.DateTime> ngaythuchien
		{
			get
			{
				return this._ngaythuchien;
			}
			set
			{
				if ((this._ngaythuchien != value))
				{
					this.OnngaythuchienChanging(value);
					this.SendPropertyChanging();
					this._ngaythuchien = value;
					this.SendPropertyChanged("ngaythuchien");
					this.OnngaythuchienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lydodoiphong", DbType="NVarChar(100)")]
		public string lydodoiphong
		{
			get
			{
				return this._lydodoiphong;
			}
			set
			{
				if ((this._lydodoiphong != value))
				{
					this.OnlydodoiphongChanging(value);
					this.SendPropertyChanging();
					this._lydodoiphong = value;
					this.SendPropertyChanged("lydodoiphong");
					this.OnlydodoiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_doiphong", Storage="_nhanvien", ThisKey="id_nhanvien_thuchien", OtherKey="id_nhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.doiphongs.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.doiphongs.Add(this);
						this._id_nhanvien_thuchien = value.id_nhanvien;
					}
					else
					{
						this._id_nhanvien_thuchien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_hoadon;
		
		private string _id_datphong;
		
		private string _id_nhanvien;
		
		private string _id_khachhang;
		
		private System.Nullable<System.DateTime> _ngay_lap;
		
		private double _TongTienHD;
		
		private EntityRef<datphong> _datphong;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_hoadonChanging(int value);
    partial void Onid_hoadonChanged();
    partial void Onid_datphongChanging(string value);
    partial void Onid_datphongChanged();
    partial void Onid_nhanvienChanging(string value);
    partial void Onid_nhanvienChanged();
    partial void Onid_khachhangChanging(string value);
    partial void Onid_khachhangChanged();
    partial void Onngay_lapChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_lapChanged();
    partial void OnTongTienHDChanging(double value);
    partial void OnTongTienHDChanged();
    #endregion
		
		public hoadon()
		{
			this._datphong = default(EntityRef<datphong>);
			this._khachhang = default(EntityRef<khachhang>);
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_hoadon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_hoadon
		{
			get
			{
				return this._id_hoadon;
			}
			set
			{
				if ((this._id_hoadon != value))
				{
					this.Onid_hoadonChanging(value);
					this.SendPropertyChanging();
					this._id_hoadon = value;
					this.SendPropertyChanged("id_hoadon");
					this.Onid_hoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_datphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_datphong
		{
			get
			{
				return this._id_datphong;
			}
			set
			{
				if ((this._id_datphong != value))
				{
					if (this._datphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_datphongChanging(value);
					this.SendPropertyChanging();
					this._id_datphong = value;
					this.SendPropertyChanged("id_datphong");
					this.Onid_datphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string id_khachhang
		{
			get
			{
				return this._id_khachhang;
			}
			set
			{
				if ((this._id_khachhang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_khachhangChanging(value);
					this.SendPropertyChanging();
					this._id_khachhang = value;
					this.SendPropertyChanged("id_khachhang");
					this.Onid_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_lap", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_lap
		{
			get
			{
				return this._ngay_lap;
			}
			set
			{
				if ((this._ngay_lap != value))
				{
					this.Onngay_lapChanging(value);
					this.SendPropertyChanging();
					this._ngay_lap = value;
					this.SendPropertyChanged("ngay_lap");
					this.Onngay_lapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienHD", DbType="Float NOT NULL")]
		public double TongTienHD
		{
			get
			{
				return this._TongTienHD;
			}
			set
			{
				if ((this._TongTienHD != value))
				{
					this.OnTongTienHDChanging(value);
					this.SendPropertyChanging();
					this._TongTienHD = value;
					this.SendPropertyChanged("TongTienHD");
					this.OnTongTienHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="datphong_hoadon", Storage="_datphong", ThisKey="id_datphong", OtherKey="id_datphong", IsForeignKey=true)]
		public datphong datphong
		{
			get
			{
				return this._datphong.Entity;
			}
			set
			{
				datphong previousValue = this._datphong.Entity;
				if (((previousValue != value) 
							|| (this._datphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._datphong.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._datphong.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._id_datphong = value.id_datphong;
					}
					else
					{
						this._id_datphong = default(string);
					}
					this.SendPropertyChanged("datphong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_khachhang", ThisKey="id_khachhang", OtherKey="id_khachhang", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._id_khachhang = value.id_khachhang;
					}
					else
					{
						this._id_khachhang = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hoadon", Storage="_nhanvien", ThisKey="id_nhanvien", OtherKey="id_nhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._id_nhanvien = value.id_nhanvien;
					}
					else
					{
						this._id_nhanvien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_khachhang;
		
		private string _ten_khachhang;
		
		private System.DateTime _ngay_sinh;
		
		private string _dia_chi;
		
		private string _sdt;
		
		private string _cmnd;
		
		private string _gioi_tinh;
		
		private string _email_khachhang;
		
		private EntitySet<datphong> _datphongs;
		
		private EntitySet<hoadon> _hoadons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_khachhangChanging(string value);
    partial void Onid_khachhangChanged();
    partial void Onten_khachhangChanging(string value);
    partial void Onten_khachhangChanged();
    partial void Onngay_sinhChanging(System.DateTime value);
    partial void Onngay_sinhChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void Onemail_khachhangChanging(string value);
    partial void Onemail_khachhangChanged();
    #endregion
		
		public khachhang()
		{
			this._datphongs = new EntitySet<datphong>(new Action<datphong>(this.attach_datphongs), new Action<datphong>(this.detach_datphongs));
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_khachhang
		{
			get
			{
				return this._id_khachhang;
			}
			set
			{
				if ((this._id_khachhang != value))
				{
					this.Onid_khachhangChanging(value);
					this.SendPropertyChanging();
					this._id_khachhang = value;
					this.SendPropertyChanged("id_khachhang");
					this.Onid_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_khachhang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_khachhang
		{
			get
			{
				return this._ten_khachhang;
			}
			set
			{
				if ((this._ten_khachhang != value))
				{
					this.Onten_khachhangChanging(value);
					this.SendPropertyChanging();
					this._ten_khachhang = value;
					this.SendPropertyChanged("ten_khachhang");
					this.Onten_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date NOT NULL")]
		public System.DateTime ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_khachhang", DbType="VarChar(50)")]
		public string email_khachhang
		{
			get
			{
				return this._email_khachhang;
			}
			set
			{
				if ((this._email_khachhang != value))
				{
					this.Onemail_khachhangChanging(value);
					this.SendPropertyChanging();
					this._email_khachhang = value;
					this.SendPropertyChanged("email_khachhang");
					this.Onemail_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_datphong", Storage="_datphongs", ThisKey="id_khachhang", OtherKey="id_khachhang")]
		public EntitySet<datphong> datphongs
		{
			get
			{
				return this._datphongs;
			}
			set
			{
				this._datphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_hoadons", ThisKey="id_khachhang", OtherKey="id_khachhang")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachsan")]
	public partial class khachsan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ten;
		
		private string _dia_chi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    #endregion
		
		public khachsan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiphong")]
	public partial class loaiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_loaiphong;
		
		private string _ten_loai;
		
		private int _gia;
		
		private EntitySet<phong> _phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_loaiphongChanging(int value);
    partial void Onid_loaiphongChanged();
    partial void Onten_loaiChanging(string value);
    partial void Onten_loaiChanged();
    partial void OngiaChanging(int value);
    partial void OngiaChanged();
    #endregion
		
		public loaiphong()
		{
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loaiphong", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_loaiphong
		{
			get
			{
				return this._id_loaiphong;
			}
			set
			{
				if ((this._id_loaiphong != value))
				{
					this.Onid_loaiphongChanging(value);
					this.SendPropertyChanging();
					this._id_loaiphong = value;
					this.SendPropertyChanged("id_loaiphong");
					this.Onid_loaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_loai
		{
			get
			{
				return this._ten_loai;
			}
			set
			{
				if ((this._ten_loai != value))
				{
					this.Onten_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_loai = value;
					this.SendPropertyChanged("ten_loai");
					this.Onten_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Int NOT NULL")]
		public int gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_phongs", ThisKey="id_loaiphong", OtherKey="id_loaiphong")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_nhanvien;
		
		private string _ten_nhanvien;
		
		private System.DateTime _ngay_sinh;
		
		private string _sdt;
		
		private string _gioi_tinh;
		
		private string _email;
		
		private System.Data.Linq.Binary _hinh_anh;
		
		private string _ten_dang_nhap;
		
		private string _mat_khau;
		
		private int _quyen;
		
		private System.Nullable<bool> _trangthai;
		
		private EntitySet<datphong> _datphongs;
		
		private EntitySet<doiphong> _doiphongs;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntityRef<quyen> _quyen1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhanvienChanging(string value);
    partial void Onid_nhanvienChanged();
    partial void Onten_nhanvienChanging(string value);
    partial void Onten_nhanvienChanged();
    partial void Onngay_sinhChanging(System.DateTime value);
    partial void Onngay_sinhChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onhinh_anhChanging(System.Data.Linq.Binary value);
    partial void Onhinh_anhChanged();
    partial void Onten_dang_nhapChanging(string value);
    partial void Onten_dang_nhapChanged();
    partial void Onmat_khauChanging(string value);
    partial void Onmat_khauChanged();
    partial void OnquyenChanging(int value);
    partial void OnquyenChanged();
    partial void OntrangthaiChanging(System.Nullable<bool> value);
    partial void OntrangthaiChanged();
    #endregion
		
		public nhanvien()
		{
			this._datphongs = new EntitySet<datphong>(new Action<datphong>(this.attach_datphongs), new Action<datphong>(this.detach_datphongs));
			this._doiphongs = new EntitySet<doiphong>(new Action<doiphong>(this.attach_doiphongs), new Action<doiphong>(this.detach_doiphongs));
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._quyen1 = default(EntityRef<quyen>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_nhanvien
		{
			get
			{
				return this._id_nhanvien;
			}
			set
			{
				if ((this._id_nhanvien != value))
				{
					this.Onid_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien = value;
					this.SendPropertyChanged("id_nhanvien");
					this.Onid_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nhanvien", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_nhanvien
		{
			get
			{
				return this._ten_nhanvien;
			}
			set
			{
				if ((this._ten_nhanvien != value))
				{
					this.Onten_nhanvienChanging(value);
					this.SendPropertyChanging();
					this._ten_nhanvien = value;
					this.SendPropertyChanged("ten_nhanvien");
					this.Onten_nhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date NOT NULL")]
		public System.DateTime ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(6) NOT NULL", CanBeNull=false)]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinh_anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary hinh_anh
		{
			get
			{
				return this._hinh_anh;
			}
			set
			{
				if ((this._hinh_anh != value))
				{
					this.Onhinh_anhChanging(value);
					this.SendPropertyChanging();
					this._hinh_anh = value;
					this.SendPropertyChanged("hinh_anh");
					this.Onhinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dang_nhap", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_dang_nhap
		{
			get
			{
				return this._ten_dang_nhap;
			}
			set
			{
				if ((this._ten_dang_nhap != value))
				{
					this.Onten_dang_nhapChanging(value);
					this.SendPropertyChanging();
					this._ten_dang_nhap = value;
					this.SendPropertyChanged("ten_dang_nhap");
					this.Onten_dang_nhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mat_khau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mat_khau
		{
			get
			{
				return this._mat_khau;
			}
			set
			{
				if ((this._mat_khau != value))
				{
					this.Onmat_khauChanging(value);
					this.SendPropertyChanging();
					this._mat_khau = value;
					this.SendPropertyChanged("mat_khau");
					this.Onmat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="Int NOT NULL")]
		public int quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					if (this._quyen1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_datphong", Storage="_datphongs", ThisKey="id_nhanvien", OtherKey="id_nhanvien")]
		public EntitySet<datphong> datphongs
		{
			get
			{
				return this._datphongs;
			}
			set
			{
				this._datphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_doiphong", Storage="_doiphongs", ThisKey="id_nhanvien", OtherKey="id_nhanvien_thuchien")]
		public EntitySet<doiphong> doiphongs
		{
			get
			{
				return this._doiphongs;
			}
			set
			{
				this._doiphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hoadon", Storage="_hoadons", ThisKey="id_nhanvien", OtherKey="id_nhanvien")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quyen_nhanvien", Storage="_quyen1", ThisKey="quyen", OtherKey="id_quyen", IsForeignKey=true)]
		public quyen quyen1
		{
			get
			{
				return this._quyen1.Entity;
			}
			set
			{
				quyen previousValue = this._quyen1.Entity;
				if (((previousValue != value) 
							|| (this._quyen1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._quyen1.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._quyen1.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._quyen = value.id_quyen;
					}
					else
					{
						this._quyen = default(int);
					}
					this.SendPropertyChanged("quyen1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
		
		private void attach_doiphongs(doiphong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_doiphongs(doiphong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quyen")]
	public partial class quyen : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_quyen;
		
		private string _ten_quyen;
		
		private EntitySet<nhanvien> _nhanviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_quyenChanging(int value);
    partial void Onid_quyenChanged();
    partial void Onten_quyenChanging(string value);
    partial void Onten_quyenChanged();
    #endregion
		
		public quyen()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_quyen", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_quyen
		{
			get
			{
				return this._id_quyen;
			}
			set
			{
				if ((this._id_quyen != value))
				{
					this.Onid_quyenChanging(value);
					this.SendPropertyChanging();
					this._id_quyen = value;
					this.SendPropertyChanged("id_quyen");
					this.Onid_quyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_quyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_quyen
		{
			get
			{
				return this._ten_quyen;
			}
			set
			{
				if ((this._ten_quyen != value))
				{
					this.Onten_quyenChanging(value);
					this.SendPropertyChanging();
					this._ten_quyen = value;
					this.SendPropertyChanged("ten_quyen");
					this.Onten_quyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="quyen_nhanvien", Storage="_nhanviens", ThisKey="id_quyen", OtherKey="quyen")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.quyen1 = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.quyen1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phong")]
	public partial class phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_phong;
		
		private int _id_loaiphong;
		
		private string _ten;
		
		private int _so_luong_nguoi;
		
		private string _trang_thai;
		
		private string _MoTa;
		
		private string _DienTich;
		
		private string _Giuong;
		
		private string _HinhAnh;
		
		private EntitySet<datphong> _datphongs;
		
		private EntityRef<loaiphong> _loaiphong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_phongChanging(string value);
    partial void Onid_phongChanged();
    partial void Onid_loaiphongChanging(int value);
    partial void Onid_loaiphongChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void Onso_luong_nguoiChanging(int value);
    partial void Onso_luong_nguoiChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnDienTichChanging(string value);
    partial void OnDienTichChanged();
    partial void OnGiuongChanging(string value);
    partial void OnGiuongChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    #endregion
		
		public phong()
		{
			this._datphongs = new EntitySet<datphong>(new Action<datphong>(this.attach_datphongs), new Action<datphong>(this.detach_datphongs));
			this._loaiphong = default(EntityRef<loaiphong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_phong
		{
			get
			{
				return this._id_phong;
			}
			set
			{
				if ((this._id_phong != value))
				{
					this.Onid_phongChanging(value);
					this.SendPropertyChanging();
					this._id_phong = value;
					this.SendPropertyChanged("id_phong");
					this.Onid_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_loaiphong", DbType="Int NOT NULL")]
		public int id_loaiphong
		{
			get
			{
				return this._id_loaiphong;
			}
			set
			{
				if ((this._id_loaiphong != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_loaiphongChanging(value);
					this.SendPropertyChanging();
					this._id_loaiphong = value;
					this.SendPropertyChanged("id_loaiphong");
					this.Onid_loaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong_nguoi", DbType="Int NOT NULL")]
		public int so_luong_nguoi
		{
			get
			{
				return this._so_luong_nguoi;
			}
			set
			{
				if ((this._so_luong_nguoi != value))
				{
					this.Onso_luong_nguoiChanging(value);
					this.SendPropertyChanging();
					this._so_luong_nguoi = value;
					this.SendPropertyChanged("so_luong_nguoi");
					this.Onso_luong_nguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="NVarChar(30)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(MAX)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giuong", DbType="NVarChar(50)")]
		public string Giuong
		{
			get
			{
				return this._Giuong;
			}
			set
			{
				if ((this._Giuong != value))
				{
					this.OnGiuongChanging(value);
					this.SendPropertyChanging();
					this._Giuong = value;
					this.SendPropertyChanged("Giuong");
					this.OnGiuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="VarChar(50)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_datphong", Storage="_datphongs", ThisKey="id_phong", OtherKey="id_phong")]
		public EntitySet<datphong> datphongs
		{
			get
			{
				return this._datphongs;
			}
			set
			{
				this._datphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_loaiphong", ThisKey="id_loaiphong", OtherKey="id_loaiphong", IsForeignKey=true)]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._id_loaiphong = value.id_loaiphong;
					}
					else
					{
						this._id_loaiphong = default(int);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.phong = this;
		}
		
		private void detach_datphongs(datphong entity)
		{
			this.SendPropertyChanging();
			entity.phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThaoTacDatPhong")]
	public partial class ThaoTacDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_lichsudatphong;
		
		private string _id_khachhang;
		
		private string _id_nhanvien_datphong;
		
		private string _id_nhanvien_thuchien;
		
		private string _id_phong;
		
		private string _tenphong;
		
		private System.Nullable<int> _loaiphong;
		
		private System.Nullable<double> _giaphong;
		
		private System.Nullable<double> _datcoc;
		
		private System.Nullable<System.DateTime> _ngaydatphong;
		
		private System.Nullable<System.DateTime> _ngay_check_in;
		
		private System.Nullable<System.DateTime> _ngay_check_out;
		
		private string _nguoithuchien;
		
		private System.Nullable<System.DateTime> _thoigianthuchien;
		
		private System.Nullable<bool> _trangthai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_lichsudatphongChanging(int value);
    partial void Onid_lichsudatphongChanged();
    partial void Onid_khachhangChanging(string value);
    partial void Onid_khachhangChanged();
    partial void Onid_nhanvien_datphongChanging(string value);
    partial void Onid_nhanvien_datphongChanged();
    partial void Onid_nhanvien_thuchienChanging(string value);
    partial void Onid_nhanvien_thuchienChanged();
    partial void Onid_phongChanging(string value);
    partial void Onid_phongChanged();
    partial void OntenphongChanging(string value);
    partial void OntenphongChanged();
    partial void OnloaiphongChanging(System.Nullable<int> value);
    partial void OnloaiphongChanged();
    partial void OngiaphongChanging(System.Nullable<double> value);
    partial void OngiaphongChanged();
    partial void OndatcocChanging(System.Nullable<double> value);
    partial void OndatcocChanged();
    partial void OnngaydatphongChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydatphongChanged();
    partial void Onngay_check_inChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_check_inChanged();
    partial void Onngay_check_outChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_check_outChanged();
    partial void OnnguoithuchienChanging(string value);
    partial void OnnguoithuchienChanged();
    partial void OnthoigianthuchienChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigianthuchienChanged();
    partial void OntrangthaiChanging(System.Nullable<bool> value);
    partial void OntrangthaiChanged();
    #endregion
		
		public ThaoTacDatPhong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_lichsudatphong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_lichsudatphong
		{
			get
			{
				return this._id_lichsudatphong;
			}
			set
			{
				if ((this._id_lichsudatphong != value))
				{
					this.Onid_lichsudatphongChanging(value);
					this.SendPropertyChanging();
					this._id_lichsudatphong = value;
					this.SendPropertyChanged("id_lichsudatphong");
					this.Onid_lichsudatphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_khachhang", DbType="VarChar(10)")]
		public string id_khachhang
		{
			get
			{
				return this._id_khachhang;
			}
			set
			{
				if ((this._id_khachhang != value))
				{
					this.Onid_khachhangChanging(value);
					this.SendPropertyChanging();
					this._id_khachhang = value;
					this.SendPropertyChanged("id_khachhang");
					this.Onid_khachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien_datphong", DbType="VarChar(10)")]
		public string id_nhanvien_datphong
		{
			get
			{
				return this._id_nhanvien_datphong;
			}
			set
			{
				if ((this._id_nhanvien_datphong != value))
				{
					this.Onid_nhanvien_datphongChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien_datphong = value;
					this.SendPropertyChanged("id_nhanvien_datphong");
					this.Onid_nhanvien_datphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhanvien_thuchien", DbType="VarChar(10)")]
		public string id_nhanvien_thuchien
		{
			get
			{
				return this._id_nhanvien_thuchien;
			}
			set
			{
				if ((this._id_nhanvien_thuchien != value))
				{
					this.Onid_nhanvien_thuchienChanging(value);
					this.SendPropertyChanging();
					this._id_nhanvien_thuchien = value;
					this.SendPropertyChanged("id_nhanvien_thuchien");
					this.Onid_nhanvien_thuchienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_phong", DbType="VarChar(10)")]
		public string id_phong
		{
			get
			{
				return this._id_phong;
			}
			set
			{
				if ((this._id_phong != value))
				{
					this.Onid_phongChanging(value);
					this.SendPropertyChanging();
					this._id_phong = value;
					this.SendPropertyChanged("id_phong");
					this.Onid_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenphong", DbType="NVarChar(50)")]
		public string tenphong
		{
			get
			{
				return this._tenphong;
			}
			set
			{
				if ((this._tenphong != value))
				{
					this.OntenphongChanging(value);
					this.SendPropertyChanging();
					this._tenphong = value;
					this.SendPropertyChanged("tenphong");
					this.OntenphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiphong", DbType="Int")]
		public System.Nullable<int> loaiphong
		{
			get
			{
				return this._loaiphong;
			}
			set
			{
				if ((this._loaiphong != value))
				{
					this.OnloaiphongChanging(value);
					this.SendPropertyChanging();
					this._loaiphong = value;
					this.SendPropertyChanged("loaiphong");
					this.OnloaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaphong", DbType="Float")]
		public System.Nullable<double> giaphong
		{
			get
			{
				return this._giaphong;
			}
			set
			{
				if ((this._giaphong != value))
				{
					this.OngiaphongChanging(value);
					this.SendPropertyChanging();
					this._giaphong = value;
					this.SendPropertyChanged("giaphong");
					this.OngiaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datcoc", DbType="Float")]
		public System.Nullable<double> datcoc
		{
			get
			{
				return this._datcoc;
			}
			set
			{
				if ((this._datcoc != value))
				{
					this.OndatcocChanging(value);
					this.SendPropertyChanging();
					this._datcoc = value;
					this.SendPropertyChanged("datcoc");
					this.OndatcocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydatphong", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydatphong
		{
			get
			{
				return this._ngaydatphong;
			}
			set
			{
				if ((this._ngaydatphong != value))
				{
					this.OnngaydatphongChanging(value);
					this.SendPropertyChanging();
					this._ngaydatphong = value;
					this.SendPropertyChanged("ngaydatphong");
					this.OnngaydatphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_check_in", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_check_in
		{
			get
			{
				return this._ngay_check_in;
			}
			set
			{
				if ((this._ngay_check_in != value))
				{
					this.Onngay_check_inChanging(value);
					this.SendPropertyChanging();
					this._ngay_check_in = value;
					this.SendPropertyChanged("ngay_check_in");
					this.Onngay_check_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_check_out", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_check_out
		{
			get
			{
				return this._ngay_check_out;
			}
			set
			{
				if ((this._ngay_check_out != value))
				{
					this.Onngay_check_outChanging(value);
					this.SendPropertyChanging();
					this._ngay_check_out = value;
					this.SendPropertyChanged("ngay_check_out");
					this.Onngay_check_outChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nguoithuchien", DbType="NVarChar(50)")]
		public string nguoithuchien
		{
			get
			{
				return this._nguoithuchien;
			}
			set
			{
				if ((this._nguoithuchien != value))
				{
					this.OnnguoithuchienChanging(value);
					this.SendPropertyChanging();
					this._nguoithuchien = value;
					this.SendPropertyChanged("nguoithuchien");
					this.OnnguoithuchienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigianthuchien", DbType="Date")]
		public System.Nullable<System.DateTime> thoigianthuchien
		{
			get
			{
				return this._thoigianthuchien;
			}
			set
			{
				if ((this._thoigianthuchien != value))
				{
					this.OnthoigianthuchienChanging(value);
					this.SendPropertyChanging();
					this._thoigianthuchien = value;
					this.SendPropertyChanged("thoigianthuchien");
					this.OnthoigianthuchienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="Bit")]
		public System.Nullable<bool> trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.thietbi")]
	public partial class thietbi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_thietbi;
		
		private string _ten_thietbi;
		
		private int _gia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_thietbiChanging(string value);
    partial void Onid_thietbiChanged();
    partial void Onten_thietbiChanging(string value);
    partial void Onten_thietbiChanged();
    partial void OngiaChanging(int value);
    partial void OngiaChanged();
    #endregion
		
		public thietbi()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_thietbi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_thietbi
		{
			get
			{
				return this._id_thietbi;
			}
			set
			{
				if ((this._id_thietbi != value))
				{
					this.Onid_thietbiChanging(value);
					this.SendPropertyChanging();
					this._id_thietbi = value;
					this.SendPropertyChanged("id_thietbi");
					this.Onid_thietbiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_thietbi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_thietbi
		{
			get
			{
				return this._ten_thietbi;
			}
			set
			{
				if ((this._ten_thietbi != value))
				{
					this.Onten_thietbiChanging(value);
					this.SendPropertyChanging();
					this._ten_thietbi = value;
					this.SendPropertyChanged("ten_thietbi");
					this.Onten_thietbiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Int NOT NULL")]
		public int gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
